# Numpy
Numpy is one of the most-widely used package for scientific computing. It's core data-type is ndarray(N Dimensional Array) object. It is very useful in linear algebra computations.<br><br>
**ndarray** is a table/list of elements of all the same type, usually numbers.


In [1]:
#importing Numpy module as np
#np is a short name that will be used throughout, whenever we refer numpy
import numpy as np

## Primitive Data-type Support
1. int :: np.int8, np.int16, np.int32, ....
2. float :: np.float8, np.float16, ....
3. uint (unsigned int)
4. short
5. double
6. long
7. complex
8. boolean

In [5]:
x = np.float(25)
x, type(x)

(25.0, float)

In [6]:
y = np.int32(4)
y, type(y)

(4, numpy.int32)

In [9]:
z = np.complex(1,2)
z, type(z)

((1+2j), complex)

Probably, You will never declare variables like the way declared above. This primitive data-types are used while declaring array, to define the type of values the array will store.

## Array Creation

In [12]:
#Creating array from list
x = np.array([2,3,1,0])
x, type(x), x.dtype

(array([2, 3, 1, 0]), numpy.ndarray, dtype('int64'))

In [16]:
#Creating array from list with type of elements specified
x = np.array([2,3,1,0], dtype=np.float16)
x, type(x), x.dtype

(array([2., 3., 1., 0.], dtype=float16), numpy.ndarray, dtype('float16'))

In [13]:
#Creating array from note mix of tuple and lists, and types
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x, type(x), x.dtype

(array([[1.+0.j, 2.+0.j],
        [0.+0.j, 0.+0.j],
        [1.+1.j, 3.+0.j]]), numpy.ndarray, dtype('complex128'))

In [18]:
#Creating array of more than one dimension
x = np.array([[1,2,3], [4,5,6]])
x, x.ndim

(array([[1, 2, 3],
        [4, 5, 6]]), 2)

In [19]:
x = np.array([1,2,3])
y = np.array([1,2,3], ndmin=2)
x.ndim, y.ndim

(1, 2)

### Using in-built functions

In [20]:
#np.zeroes :: Creates array of zeroes of desired dimension
#default dtype is float64
z = np.zeros((5, 2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
#np.ones :: Creates array of ones of desired dimension
o = np.ones((2, 5), dtype=np.int32)
o

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [23]:
#np.arrange() :: Creates array of regularly incrementing values
#start by-default 0
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#start is 2 inclusive and end is 10 exclusive
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#start 2, end 5, interval 0.5
np.arange(2, 5, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [33]:
#np.linspace() :: Creates an array of desired number of elements within a range
np.linspace(0, 100, 11, dtype=np.int32)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int32)

### Creating array of random elements
https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

In [35]:
#Creates array of given shape with random values 
#from uniform distribution over [0, 1)

np.random.rand(2, 5)

array([[0.81678331, 0.79116235, 0.21293392, 0.34003647, 0.53261902],
       [0.70970861, 0.89505039, 0.86900805, 0.16403307, 0.16007014]])

In [38]:
#Array of random integers of size (5, 2)
#Values between [0, 100)
np.random.randint(0, 100, (5,2))

array([[47, 80],
       [54, 66],
       [14, 32],
       [37, 57],
       [13, 93]])

In [39]:
#Creates array of random floats in the half-open interval [0.0, 1.0).
np.random.sample((2,5))

array([[0.80245095, 0.22146987, 0.36990363, 0.05137121, 0.13172364],
       [0.68460067, 0.88068292, 0.86739425, 0.6197589 , 0.31958883]])

Some other functions to create array: <br>
zeros_like, ones_like, empty, empty_like, numpy.random.randn, etc

### ndarray attributes

In [87]:
Z = np.random.rand(5,4)

In [88]:
#Dimension
Z.ndim

2

In [89]:
#shape
Z.shape

(5, 4)

In [90]:
#size
Z.size

20

In [91]:
#dtype of elements
Z.dtype, Z.dtype.name

(dtype('float64'), 'float64')

In [92]:
Z

array([[0.2481395 , 0.1983528 , 0.0410161 , 0.20810922],
       [0.48233272, 0.8987761 , 0.59439364, 0.27459744],
       [0.8389128 , 0.15940109, 0.97007028, 0.11382461],
       [0.049994  , 0.12193927, 0.88452954, 0.88462284],
       [0.85188557, 0.01866635, 0.54707693, 0.28003555]])

In [93]:
type(Z)

numpy.ndarray

In [94]:
#Printing ndarray :: Python print function
print(Z)

[[0.2481395  0.1983528  0.0410161  0.20810922]
 [0.48233272 0.8987761  0.59439364 0.27459744]
 [0.8389128  0.15940109 0.97007028 0.11382461]
 [0.049994   0.12193927 0.88452954 0.88462284]
 [0.85188557 0.01866635 0.54707693 0.28003555]]


## Some Basic Operations

In [95]:
x = np.array([10, 20, 30, 40])
y = np.linspace(0, 3, 4, dtype=np.int32)
x, y

(array([10, 20, 30, 40]), array([0, 1, 2, 3], dtype=int32))

In [96]:
#Element-wise addition
a = x + y
a

array([10, 21, 32, 43])

In [97]:
#Element-wise multiplication
m = x * y
m

array([  0,  20,  60, 120])

In [98]:
#Using in-built mathematical function (sin) and constant (pi)
np.sin(np.pi*y)

array([ 0.0000000e+00,  1.2246468e-16, -2.4492936e-16,  3.6739404e-16])

In [99]:
s = y**2
s

array([0, 1, 4, 9], dtype=int32)

In [100]:
r = np.random.randint(0, 100, 11)
r

array([88, 90, 16, 75,  0, 87, 30, 98, 11,  2, 53])

In [101]:
#Some statistical Measures
np.sum(r), np.max(r), np. min(r), np.mean(r), np.median(r)
#Explore rest

(550, 98, 0, 50.0, 53.0)

In [102]:
np.exp(np.random.randn(2,4))

array([[7.21063321, 6.441903  , 0.69593099, 0.32257122],
       [1.08277713, 4.17748436, 1.61820488, 2.1713538 ]])

In [103]:
#Results boolean array of those satisfying the condition
r>50

array([ True,  True, False,  True, False,  True, False,  True, False,
       False,  True])

## Reshaping an array

In [114]:
n = np.arange(12)
n, n.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [113]:
N = n.reshape(3,4)
N, N.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (3, 4))

## Multi-dimensional Arrays

In [107]:
#2-d array or Matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
np.ones((3,3,3), dtype=np.int32)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [109]:
#Diagonal Matrix
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [110]:
#Similar to mesh grid in MATLAB
x, y = np.mgrid[0:5, 0:5]

In [111]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [112]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Indexing
Indexing element can be done using square brackets [ ]. <br>
Index starts from 0.

In [116]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [147]:
# n is 1d array, [index]
#index ::  0 to len(array)-1
#negitive indices starts from end
n[5], n[-1]

(5, 11)

In [136]:
#Manipulating Value at a particular position
n[0] = -1
print(n)

[-1  1  2  3  4  5  6  7  8  9 10 11]


In [126]:
print(N)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [128]:
#N is 2d array
#[row, col]
N[1,1]

5

In [130]:
#If only one value inside the [], returns the entire row
N[2]
#Equivalent to N[2:]

array([ 8,  9, 10, 11])

In [131]:
N[2:]  #Row 3

array([[ 8,  9, 10, 11]])

In [133]:
#Fetching an entire column
N[:,1]  #Col 2

array([1, 5, 9])

In [139]:
#Assigning 23 to element at location: 2nd row and 4th column
N[2,3] = 23
N

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 23]])

## Slicing
Extracting a part of an array

In [140]:
#Accessing elements from index 2 to index 4
n[2:5]

array([2, 3, 4])

In [141]:
n[3:5] = [34, 45]
n

array([-1,  1,  2, 34, 45,  5,  6,  7,  8,  9, 10, 11])

In [152]:
#No lower bound and upper bound involved, stride is 2
n[::2]

array([-1,  2, 45,  6,  8, 10])

In [153]:
#Index Slicing Works Similarly for multi-dimensional Array
N[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 23]])

In [154]:
#Extracting a 3x3 Matrix from N
M = N[0:3, 0:3]
print(M)
print(M.ndim)
print(M.shape)
print(M.size)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
2
(3, 3)
9


In [162]:
M[0:2, 0:2] = np.arange(1,5).reshape(2,2)
M

array([[ 1,  2,  2],
       [ 3,  4,  6],
       [ 8,  9, 10]])

In [167]:
Mat = np.arange(20).reshape(5,4)
print(Mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [168]:
print(Mat[::2, ::2])

[[ 0  2]
 [ 8 10]
 [16 18]]


## Broadcasting
The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [169]:
a = np.array([1, 2, 3, 4])
b = 5
print(a*b)

[ 5 10 15 20]


We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as a. The new elements in b are simply copies of the original scalar.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when
1. they are equal
2. one of them is 1

Let's assume you want do some computation involving 4d and 3d Matrices,<br>
A(4d a):    8 x 1 x 6 x 1<br>
B(3d a):        5 x 6 x 3<br>
Result :    8 x 5 x 6 x 3

In [171]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = xx + y
print(z)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [172]:
xx.shape, y.shape, z.shape

((4, 1), (5,), (4, 5))

## Linear Algebra

In [173]:
#Vectors :: 1d Array
v1 = np.array([2, 5, 0, 4])
v2 = np.array([1, 9, 9, 1])

The standard arithmetic operators (+, -, *) can be used to perform Vector/Matrix operations

In [174]:
#Vector Sum
v1 + v2

array([ 3, 14,  9,  5])

In [175]:
#Multiplication with Scalar
v1 * 5

array([10, 25,  0, 20])

In [176]:
#Dot Product
v1.dot(v2)

51

In [180]:
M = np.matrix(N[0:3,0:3])
M

matrix([[ 1,  2,  2],
        [ 3,  4,  6],
        [ 8,  9, 10]])

In [182]:
#Matrix Multiplication 1
M2 = np.dot(M, M)
M2

matrix([[ 23,  28,  34],
        [ 63,  76,  90],
        [115, 142, 170]])

In [183]:
#Matrix Multiplication 2
M*M

matrix([[ 23,  28,  34],
        [ 63,  76,  90],
        [115, 142, 170]])

In [202]:
V = np.matrix(v1[0:3]).reshape(3,1)
V

matrix([[2],
        [5],
        [0]])

In [200]:
#Matrix Vector Multiplication
print(M*V

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [194]:
#Transpose
M.T

matrix([[ 1,  3,  8],
        [ 2,  4,  9],
        [ 2,  6, 10]])

In [195]:
#Transpose 2
np.transpose(M)

matrix([[ 1,  3,  8],
        [ 2,  4,  9],
        [ 2,  6, 10]])

In [196]:
#Inverse of a Matrix
np.linalg.inv(M)

matrix([[-1.16666667e+00, -1.66666667e-01,  3.33333333e-01],
        [ 1.50000000e+00, -5.00000000e-01, -3.17206578e-17],
        [-4.16666667e-01,  5.83333333e-01, -1.66666667e-01]])

In [197]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])