# Tensorflow 
Open source library for numerical computation using data flow graph. Created and Maintained by Google.<br><br>
Tensorflow got it's name from **tensor**, array of arbitrary dmensions. Using Tensorflow, one can manipulate tensors with higher dimensions.

## Why Tensorflow?
1. Efficient
2. Scalable
3. Maintainable
4. Portable
5. Flexible
6. Visualization in TensorBoard
7. Easy to save and restore models

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf

## How Tensorflow works?
Tensorflow operations creates, destroys, and manipulates tensors. All the computation can be operations can be easily visualized using *computation graph* or *data flow graph*.<br>
Graph's **nodes** are operations and **edges** are tensors. Tensors flows through graph, and gets manipulated at each node by an operation.

### Tensor
A tensor is an n-d array,
* 0-d tensor : scalar
* 1-d tensor : vector
* 2-d tensor : matrix
<br>

A tensor can be defined as a constant or a variable.

### Constants

In [2]:
s = tf.constant(24)  #scalar
v = tf.constant([1, 2, 3, 4], dtype=tf.int64, name='vector')  #vector
m = tf.constant([[1,2], [3,4]]) #matrix

## Using tf.Session() to evaluate the graph
A Session object encapsulates the environment in which memory is allocated for storing values of variables, operations are executed, and tensors are evaluated.

In [3]:
#Creating a graph
g = tf.Graph()

#Setting the generated graph as default graph
with g.as_default():
    x = tf.constant(5, name="x")
    y = tf.constant(4, name="y")
    
    add = tf.add(x, y, name="add")
    mul = tf.multiply(x, y, name="mul")
    
    with tf.Session() as sess:
        print(add)
        print(mul.eval())

Tensor("add:0", shape=(), dtype=int32)
20


In [4]:
g = tf.Graph()

with g.as_default():
    x = tf.constant(5, name="x")
    y = tf.constant(4, name="y")
    
    add = tf.add(x, y, name="add")
    mul = tf.multiply(x, y, name="mul")
    
    with tf.Session() as sess:
        #sess.run(fetchees) will help you fetch multiple values, eval() cannot.
        a, m = sess.run(fetches=[add, mul])
        print(a)
        print(m)

9
20


### Variables

In [5]:
#Creating variable using Variable object
v_s = tf.Variable(5)
v_v = tf.Variable([1, 2, 3, 4], dtype=tf.int32)
v_m = tf.Variable(tf.zeros([25,4]), dtype=tf.float32, name="matrix")

In [6]:
#Creating variable with tf.get_variable method
Weights = tf.get_variable("Weigts", shape=(25,4), initializer=tf.random_uniform_initializer())
Bias = tf.get_variable("Bias", initializer=tf.random.normal([25]))

In [7]:
g = tf.Graph()

with g.as_default():
    weights = tf.get_variable("Weigts", shape=(25,4), initializer=tf.random_uniform_initializer())
    bias = tf.get_variable("Bias", initializer=tf.random.normal([25]))
    
    with tf.Session() as sess:
        #initialising all variables at once
        sess.run(tf.global_variables_initializer())
        print(weights.eval())
        print(sess.run(bias))

[[0.17859161 0.662135   0.802531   0.8892286 ]
 [0.42852056 0.49400282 0.4478383  0.15403903]
 [0.9868784  0.5225543  0.35956573 0.87094367]
 [0.42644405 0.05526125 0.5771898  0.70351934]
 [0.8487822  0.52953184 0.22045517 0.3798436 ]
 [0.8742199  0.4068097  0.78645957 0.24451363]
 [0.89029527 0.05570257 0.3968346  0.10618329]
 [0.13092244 0.7392434  0.86539614 0.11351633]
 [0.15320158 0.18773556 0.80555    0.2700833 ]
 [0.3211782  0.04334092 0.20775473 0.50149536]
 [0.409405   0.8084732  0.9371854  0.05203116]
 [0.48291016 0.3844452  0.8324512  0.9114362 ]
 [0.36492896 0.48561502 0.59439087 0.37047064]
 [0.35242343 0.40764523 0.54853165 0.13580573]
 [0.26943994 0.22343302 0.7864845  0.65320015]
 [0.9292009  0.5090842  0.4413376  0.22849226]
 [0.71244705 0.629125   0.5613841  0.45466185]
 [0.07376182 0.08303785 0.47045946 0.5401523 ]
 [0.4683329  0.45486045 0.8270087  0.60877204]
 [0.9015933  0.3563552  0.22250581 0.47655463]
 [0.25416493 0.24735153 0.630803   0.07265353]
 [0.4899131  

## Visualizing Graphs using TensorBoard

In [8]:
x = tf.constant(5, name="x")
y = tf.constant(4, name="y")

add = tf.add(x, y, name="add")
mul = tf.multiply(x, y, name="mul")

with tf.Session() as sess:
    #Creates the summary writer
    #After graph definition
    #Before Session
    #Since we not created a graph explicitly,
    #Every operation is being done on default_graph
    writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
    a, m = sess.run(fetches=[add, mul])
    print(a, m)
    
#To access graph in Tensorboard
#1. Open terminal.
#2. Check for graphs folder
#3. Run: tensornoard --logdir="./graphs" --port 6006
#4. Open browser and go to: http://localhost:6006/

9 20


### Placeholders
A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data.

In [9]:
#creating a placeholder
inputs = tf.placeholder(shape=[25,4], dtype=tf.float32)

In [10]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)

In [11]:
add = a+b

In [12]:
#Value to the placeholder is provided during the run
#Using feed_dict
with tf.Session() as sess:
    res = sess.run(add, feed_dict={a:[4,4,4]})
    print(res)

[9. 9. 9.]


#### An example to show how Placeholders and Variables are created in data flow graph

In [13]:
import numpy as np

inp_data = np.linspace(0, 100, 100, dtype=np.float32).reshape(25,4)

y = tf.matmul(inputs, tf.transpose(Weights)) + Bias

with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs_linear', tf.get_default_graph())
    sess.run(tf.initialize_all_variables())
    res = sess.run(y, feed_dict={inputs:inp_data})
    print(res)