In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#helper function to summarize the properties of a tensor
def describe(x):
    print("Type :: {}".format(x.type()))
    print("Data Type :: {}".format(x.dtype))
    print("Size :: {}".format(x.size()))
    print("Shape :: {}".format(x.shape))
    print("Dimension :: {}".format(x.dim()))
    print("Data :: \n{}".format(x))

### Scalar (0-d)

In [3]:
#Scalar (o-d Tensor)
s = torch.tensor(2504)
describe(s)

Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([])
Shape :: torch.Size([])
Dimension :: 0
Data :: 
2504


### Vector (1-d)

In [4]:
#Constructing a Tensor directly using python list
m = torch.Tensor([25, 4])
describe(m)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([2])
Shape :: torch.Size([2])
Dimension :: 1
Data :: 
tensor([25.,  4.])


torch.tensor() infer the type of the data automatically, <br>
torch.Tensor() is an alias of torch.FloatTensor() <br>
prefer torch.tensor()

### Matrix (2-d)

In [5]:
#Constructing a Tensor directly 
#Creates an unitilised matrix of size 25x4
c = torch.Tensor(25,4)
describe(c)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([25, 4])
Shape :: torch.Size([25, 4])
Dimension :: 2
Data :: 
tensor([[-2.9605e+07,  4.5744e-41, -2.9605e+07,  4.5744e-41],
        [ 1.1910e+14, -1.0310e-10, -3.1337e+07,  4.5744e-41],
        [-3.1370e+07,  4.5744e-41, -5.3531e-19,  1.4888e+38],
        [-3.1338e+07,  4.5744e-41, -3.1369e+07,  4.5744e-41],
        [ 7.3920e+14,  3.4332e-27, -2.0063e+05,  4.5744e-41],
        [ 1.4600e-38,  0.0000e+00,  4.7660e-06, -1.0084e-08],
        [-2.2964e+05,  4.5744e-41, -1.8772e+06,  4.5744e-41],
        [-2.9343e+31,  3.5991e-09,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  5.8475e-40,  2.1321e-26],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-4.9702e-30,  1.5749e+32,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.9343e+31,  3.5991e-09],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 5.8475e-40,  2.1321e-26,  0.0000e+00,  0.0000e+00]

In [6]:
#Changing Data type
m = m.int()
describe(m)

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([2])
Shape :: torch.Size([2])
Dimension :: 1
Data :: 
tensor([25,  4], dtype=torch.int32)


In [8]:
#Using torch.tensor(), can specify data types
m = torch.tensor([25, 4], dtype=torch.int32)
describe(m)

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([2])
Shape :: torch.Size([2])
Dimension :: 1
Data :: 
tensor([25,  4], dtype=torch.int32)


### Initialising using numpy array

In [10]:
#Initialized with numpy array
n = torch.tensor(np.array([25, 4], dtype=np.int32))
describe(n)

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([2])
Shape :: torch.Size([2])
Dimension :: 1
Data :: 
tensor([25,  4], dtype=torch.int32)


In [11]:
#From numpy array
a = np.random.rand(10)
tensor_a = torch.from_numpy(a)
describe(tensor_a)

Type :: torch.DoubleTensor
Data Type :: torch.float64
Size :: torch.Size([10])
Shape :: torch.Size([10])
Dimension :: 1
Data :: 
tensor([0.9465, 0.1284, 0.4673, 0.3721, 0.6517, 0.9694, 0.4873, 0.5321, 0.3029,
        0.7919], dtype=torch.float64)


In [12]:
#To numpy array
back_to_numpy_a = tensor_a.numpy()
back_to_numpy_a, back_to_numpy_a.dtype

(array([0.94654122, 0.12844508, 0.46733646, 0.37214219, 0.65169258,
        0.96942189, 0.48729477, 0.53208292, 0.30294736, 0.79190413]),
 dtype('float64'))

### Different Tensor Creation

In [14]:
#1 Empty
empt = torch.empty(10)
describe(empt)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([10])
Shape :: torch.Size([10])
Dimension :: 1
Data :: 
tensor([4.2196e-37, 0.0000e+00, 3.9913e-37, 4.4842e-44, 4.4842e-44, 3.9913e-37,
        1.5835e-43, 0.0000e+00, 4.5824e-37, 0.0000e+00])


In [15]:
#2 Zero
z = torch.zeros(2,3,4)
describe(z)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([2, 3, 4])
Shape :: torch.Size([2, 3, 4])
Dimension :: 3
Data :: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [17]:
#3 One
#torch.ones()
#Constructing a tensor using the existing Tensor
o = torch.ones_like(z)
describe(o)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([2, 3, 4])
Shape :: torch.Size([2, 3, 4])
Dimension :: 3
Data :: 
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [19]:
#4 Filled with a value
#can also create tensor filled with same value
#torch.fill(shape)
z.fill_(25) #_ ===> in-place operation
describe(z)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([2, 3, 4])
Shape :: torch.Size([2, 3, 4])
Dimension :: 3
Data :: 
tensor([[[25., 25., 25., 25.],
         [25., 25., 25., 25.],
         [25., 25., 25., 25.]],

        [[25., 25., 25., 25.],
         [25., 25., 25., 25.],
         [25., 25., 25., 25.]]])


In [20]:
#5 Diagonal Matrix
#Creating a diagonal matrix tensor using the data
d = torch.diag(torch.Tensor([1,2,3,4]))
describe(d)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([4, 4])
Shape :: torch.Size([4, 4])
Dimension :: 2
Data :: 
tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 4.]])


In [21]:
#Creating an identity matrix
i = torch.eye(5,5)
describe(i)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([5, 5])
Shape :: torch.Size([5, 5])
Dimension :: 2
Data :: 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [22]:
#Creates a tensor insitialised with 10 uniform random values
x = torch.rand(10)
describe(x)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([10])
Shape :: torch.Size([10])
Dimension :: 1
Data :: 
tensor([0.1564, 0.7739, 0.2580, 0.9800, 0.7930, 0.9585, 0.6061, 0.8082, 0.0367,
        0.1082])


In [23]:
#Creating a normal distribution tensor of shape x
x_normal = torch.randn_like(x)
describe(x_normal)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([10])
Shape :: torch.Size([10])
Dimension :: 1
Data :: 
tensor([ 0.6418, -1.5015, -0.2970,  0.3956, -1.3283,  0.5136, -0.1836,  1.2539,
        -0.4568, -0.1882])


In [24]:
# randint(start, end, size(must be a tuple))
rand_ints = torch.randint(0, 100, (5, 4))
describe(rand_ints)

Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([5, 4])
Shape :: torch.Size([5, 4])
Dimension :: 2
Data :: 
tensor([[56, 99, 76, 79],
        [36, 29, 99, 54],
        [93, 82, 78, 36],
        [ 7, 87, 15, 98],
        [56, 63, 96, 98]])


### Using Sequences

In [28]:
#linspace(start, end, number of elements)
ls = torch.linspace(20, 30, 25)
describe(ls)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([25])
Shape :: torch.Size([25])
Dimension :: 1
Data :: 
tensor([20.0000, 20.4167, 20.8333, 21.2500, 21.6667, 22.0833, 22.5000, 22.9167,
        23.3333, 23.7500, 24.1667, 24.5833, 25.0000, 25.4167, 25.8333, 26.2500,
        26.6667, 27.0833, 27.5000, 27.9167, 28.3333, 28.7500, 29.1667, 29.5833,
        30.0000])


In [33]:
#range(start, end, skip)
rg = torch.range(0, 100, 3)
describe(rg)

Type :: torch.FloatTensor
Data Type :: torch.float32
Size :: torch.Size([34])
Shape :: torch.Size([34])
Dimension :: 1
Data :: 
tensor([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
        42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78., 81.,
        84., 87., 90., 93., 96., 99.])


/home/akshay/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


### Indexing & Slicing
Accessing elements, rows, columns, sub-tensor from a tensor

In [32]:
#Indexing and Slicing
#3rd row, 2nd and 3rd column
rand_ints[2, 1:3]

tensor([82, 78])

In [ ]:
rand_ints[2, 1:3] = torch.Tensor([19, 91])
rand_ints

In [ ]:
#first column
rand_ints[:, 0]

In [ ]:
#first 2 row
rand_ints[:2,:]

In [ ]:
#last 3 column
rand_ints[:,-3:]

In [ ]:
#last row
rand_ints[-1,:]

In [34]:
#Non-contiguous indexing, access 2nd and 4th col
indices = torch.LongTensor([1,3])
describe(torch.index_select(rand_ints, dim=1, index=indices))

Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([5, 2])
Shape :: torch.Size([5, 2])
Dimension :: 2
Data :: 
tensor([[99, 79],
        [29, 54],
        [82, 36],
        [87, 98],
        [63, 98]])


In [35]:
#access 2nd and 4th row
describe(torch.index_select(rand_ints, dim=0, index=indices))

Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([2, 4])
Shape :: torch.Size([2, 4])
Dimension :: 2
Data :: 
tensor([[36, 29, 99, 54],
        [ 7, 87, 15, 98]])


### Reshaping

In [37]:
a = torch.arange(20, dtype=torch.int32)
a = a.view(2,2,5)
describe(a)

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([2, 2, 5])
Shape :: torch.Size([2, 2, 5])
Dimension :: 3
Data :: 
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]], dtype=torch.int32)


In [ ]:
#Some functions
# For 3d tensors, dim=0 represents 2D tensors, dim=1 represents rows, dim=2 represents column
a.sum(), a.sum(dim=0), a.sum(dim=1), a.sum(dim=2)

In [38]:
# -1 is inferred from other dimension
a = a.view(-1, 2)
describe(a)
a = a.view(5, -1)
describe(a)

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([10, 2])
Shape :: torch.Size([10, 2])
Dimension :: 2
Data :: 
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]], dtype=torch.int32)
Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([5, 4])
Shape :: torch.Size([5, 4])
Dimension :: 2
Data :: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=torch.int32)


In [39]:
a = a.view(4, 5)
describe(torch.cat((a,a), dim=1))
print("\n")
describe(torch.cat((a,a), dim=0))

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([4, 10])
Shape :: torch.Size([4, 10])
Dimension :: 2
Data :: 
tensor([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]], dtype=torch.int32)


Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([8, 5])
Shape :: torch.Size([8, 5])
Dimension :: 2
Data :: 
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], dtype=torch.int32)


### Loading dataset from sklearn

In [40]:
#matrix of size 506x13
from sklearn.datasets import load_boston
boston = load_boston()

boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [41]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [42]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [44]:
# from_numpy converts numpy array to pytorch tensor
boston_data = torch.from_numpy(boston.data)
boston_data.size()

torch.Size([506, 13])

In [45]:
#slicing element from columns 3 to 7 from first 2 rows of a tensor
boston_data[:2, 3:8]

tensor([[ 0.0000,  0.5380,  6.5750, 65.2000,  4.0900],
        [ 0.0000,  0.4690,  6.4210, 78.9000,  4.9671]], dtype=torch.float64)

### Arithmetic

In [46]:
#Arithmetic operations +-*/
a = torch.rand(2,2)
b = torch.rand(2,2)

c = a+b
c

tensor([[0.7445, 0.8295],
        [0.9542, 0.2731]])

In [47]:
#_ signifies for inplace operation(Here, addition)
a.add_(b)

tensor([[0.7445, 0.8295],
        [0.9542, 0.2731]])

In [48]:
one_value_tensor = torch.tensor([25], dtype=torch.int32)
describe(one_value_tensor)
one_value_tensor.item()

Type :: torch.IntTensor
Data Type :: torch.int32
Size :: torch.Size([1])
Shape :: torch.Size([1])
Dimension :: 1
Data :: 
tensor([25], dtype=torch.int32)


25

In [49]:
#Linear Algebra
x1 = torch.arange(6).view(2,3)
x2 = torch.randint(1, 11, (3,1))
print("x1", "\n============")
describe(x1)
print("============\n")
print("x2", "\n============")
describe(x2)
print("============\n")
print("x1 matmul x2", "\n============")
describe(torch.matmul(x1, x2))
print("============\n")
print("x1 transpose", "\n============")
describe(torch.transpose(x1, 0, 1))
print("============\n")

x1 
Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([2, 3])
Shape :: torch.Size([2, 3])
Dimension :: 2
Data :: 
tensor([[0, 1, 2],
        [3, 4, 5]])

x2 
Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([3, 1])
Shape :: torch.Size([3, 1])
Dimension :: 2
Data :: 
tensor([[10],
        [ 7],
        [ 4]])

x1 matmul x2 
Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([2, 1])
Shape :: torch.Size([2, 1])
Dimension :: 2
Data :: 
tensor([[15],
        [78]])

x1 transpose 
Type :: torch.LongTensor
Data Type :: torch.int64
Size :: torch.Size([3, 2])
Shape :: torch.Size([3, 2])
Dimension :: 2
Data :: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])



In [74]:
#Vector Dot Product
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])
v1.dot(v2)

tensor(32)

In [75]:
#Element wise product
v1*v2

tensor([ 4, 10, 18])

In [62]:
# Variables are wrapper around the tensor ith gradient and reference to a function that created it.
from torch.autograd import Variable
x = Variable(torch.ones(2,2), requires_grad=True)
x, x.requires_grad

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True), True)

In [51]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [52]:
print(y.grad_fn)

In [53]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [54]:
#Will give None
x.grad

In [55]:
#will calculate d(out)/dx
out.backward()

In [56]:
#Gradient wrt x
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [63]:
#Raw data
x.data

tensor([[1., 1.],
        [1., 1.]])

In [58]:
#reference to the function that has created the variable
y.grad_fn, z.grad_fn, out.grad_fn

(<AddBackward0 at 0x7f8440a8ec18>,
 <MeanBackward0 at 0x7f8440a8ef28>)

In [65]:
#Will give None
x.grad_fn

In [68]:
t = torch.ones(2,5)
t, t.requires_grad

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]), False)

In [73]:
t.requires_grad_(True)
(t**2).requires_grad

True

In [72]:
#Sometimes some parameters need not to be updated: Use with torch.no_grad()
with torch.no_grad():
    print((t**2).requires_grad)

False


### Tensor on GPU

In [ ]:
#Tensors can be moved to any device.
#Following code checks if GPU is available, maked cuda (GPU) default device.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x3 = torch.rand(2,5).to(device)
if device == "cuda":
    print(torch.cuda.get_device_name(0))
    print(x3.type())
else:
    print(device)
    print(x3.type())