In [1]:
import torch

In [2]:
tnsr = torch.Tensor([1,2,3,4,5])
tnsr

tensor([1., 2., 3., 4., 5.])

In [5]:
rnd = torch.rand(2,5)
rnd

tensor([[0.8811, 0.2235, 0.5109, 0.8174, 0.7008],
        [0.4124, 0.7505, 0.9646, 0.6398, 0.3034]])

In [6]:
zeros = torch.zeros(2,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
zeros[0][4] = 1
zeros

tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [8]:
rnd[0][4].item()

0.7008498907089233

In [9]:
rnd.size()

torch.Size([2, 5])

In [10]:
rnd.shape

torch.Size([2, 5])

In [11]:
rnd.dim()

2

In [12]:
rnd.type()

'torch.FloatTensor'

In [13]:
zeros.view(1,10)

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [18]:
import numpy as np

nd = np.random.randint(0,10,5)
print(nd, type(nd))

nd_tnsr = torch.from_numpy(nd)
print(nd_tnsr)

tnsr_nd = nd_tnsr.numpy()
print(tnsr_nd, type(tnsr_nd))

[5 4 0 1 9] <class 'numpy.ndarray'>
tensor([5, 4, 0, 1, 9])
[5 4 0 1 9] <class 'numpy.ndarray'>


In [26]:
a = torch.from_numpy(np.random.randint(0,100,(5,1)))
b = torch.from_numpy(np.random.randint(0,100,(5,1)))

print(a)
print(b)

tensor([[65],
        [22],
        [91],
        [27],
        [73]])
tensor([[ 0],
        [69],
        [22],
        [22],
        [84]])


In [31]:
a = a.t()
print(a)

tensor([[65, 22, 91, 27, 73]])


In [34]:
mat_mul = a.mm(b)
print(mat_mul)

tensor([[10246]])


In [35]:
elem_mul = torch.mul(a.t(), b)
print(elem_mul)

tensor([[   0],
        [1518],
        [2002],
        [ 594],
        [6132]])
